# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = awww-daemon
exec-once = sleep 2 && awww img "$HOME/Pictures/wp3614528-star-wars-4k-wallpapers.jpg" --transition-type none
exec-once = ~/.config/hypr/weather-update.sh
exec-once = ~/.config/hypr/lock-on-boot.sh
